In [3]:
# Preprocessing
# pip install scikit-learn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

In [8]:
# create simple dataset
data = {
    "id": [1, 2, 3, 4, 5, 6],
    "age": [25, np.nan, 30, 35, np.nan, 100],
    "Salary": [50000, 60000, np.nan, 80000, 90000, np.nan],
    "city": ["NewYork", "London", np.nan, "Paris", "London", np.nan]
}
df = pd.DataFrame(data)
print("Original Data: ")
df

Original Data:

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2    NaN  60000.0   London
2   3   30.0      NaN      NaN
3   4   35.0  80000.0    Paris
4   5    NaN  90000.0   London
5   6  100.0      NaN      NaN

In [10]:
# mean Impute
mean_imputer = SimpleImputer(strategy = 'mean')
df_mean = df.copy()
df_mean[['age','Salary']] = mean_imputer.fit_transform(df_mean[['age','Salary']])
print("Mean Imputer")
display(df_mean)

Mean Imputer

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2   47.5  60000.0   London
2   3   30.0  70000.0      NaN
3   4   35.0  80000.0    Paris
4   5   47.5  90000.0   London
5   6  100.0  70000.0      NaN

In [13]:
# median imputer
median_imputer = SimpleImputer(strategy = 'median')
df_median = df.copy()
df_median[['age','Salary']] = median_imputer.fit_transform(df_median[['age','Salary']])
print("median Imputer")
display(df_median)

median Imputer

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2   32.5  60000.0   London
2   3   30.0  70000.0      NaN
3   4   35.0  80000.0    Paris
4   5   32.5  90000.0   London
5   6  100.0  70000.0      NaN

In [14]:
# mode imputer
mode_imputer = SimpleImputer(strategy = "most_frequent")
df_mode = df.copy()
df_mode[['city']] = mode_imputer.fit_transform(df_mode[['city']])
print("mode imputer")
df_mode

mode imputer

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2    NaN  60000.0   London
2   3   30.0      NaN   London
3   4   35.0  80000.0    Paris
4   5    NaN  90000.0   London
5   6  100.0      NaN   London

In [ ]:
# scalar