In [8]:
import pandas as pd
import sqlite3

# Data Reading

In [9]:
df = pd.read_json("data.json")
df.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [10]:
df2 = pd.read_csv("mydata.csv")
df2.head()

      Name  Score   Age        Date
0    Alice   85.0  25.0  2023-01-10
1      Bob    NaN  -1.0  2023-02-15
2  Charlie   95.0  23.0  not-a-date
3    David   70.0  22.0  2023-03-20
4      Eva    NaN  21.0         NaN

In [12]:
conn = sqlite3.connect("example.db")

df3 = pd.read_sql("SELECT * FROM my_table", conn)
df3.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [7]:
df4 = pd.read_excel('data.xlsx')
df4.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [13]:
# Data Imputation
# libraries numpy, pandas, random, matplotlib, seaborn,  from sklearn.impute , import SimpleImputer

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.impute import SimpleImputer

In [3]:
import numpy as np
import pandas as pd

# Data Create - all lists have length 6
data = {
    "id": [1, 2, 3, 4, 5, 6],
    "age": [25, np.nan, 30, 35, np.nan, 100],
    "Salary": [50000, 60000, np.nan, 80000, 90000, np.nan],
    "city": ["NewYork", "London", np.nan, "Paris", "London", np.nan]
}

df = pd.DataFrame(data)
df

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2    NaN  60000.0   London
2   3   30.0      NaN      NaN
3   4   35.0  80000.0    Paris
4   5    NaN  90000.0   London
5   6  100.0      NaN      NaN

In [4]:
mean_imputer = SimpleImputer(strategy = 'mean')
df_mean = df.copy()
df_mean[['age','Salary']] = mean_imputer.fit_transform(df_mean[['age','Salary']])
display(df_mean)

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2   47.5  60000.0   London
2   3   30.0  70000.0      NaN
3   4   35.0  80000.0    Paris
4   5   47.5  90000.0   London
5   6  100.0  70000.0      NaN

In [7]:
median_imputer = SimpleImputer(strategy = 'median')
df_median = df.copy()
df_median[['age','Salary']] = median_imputer.fit_transform(df_median[['age','Salary']])
display(df_median)

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2   32.5  60000.0   London
2   3   30.0  70000.0      NaN
3   4   35.0  80000.0    Paris
4   5   32.5  90000.0   London
5   6  100.0  70000.0      NaN

In [9]:
mode_imputer = SimpleImputer(strategy = 'most_frequent')
df_mode = df.copy()
df_mode[['age','Salary',"city"]] = mode_imputer.fit_transform(df_mode[['age','Salary', "city"]])
display(df_mode)

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2   25.0  60000.0   London
2   3   30.0  50000.0   London
3   4   35.0  80000.0    Paris
4   5   25.0  90000.0   London
5   6  100.0  50000.0   London

In [10]:
df_random = df.copy()
def random_impute(series):
    # drop na values to avoid errors
    filled = series.dropna().tolist()
    return series.apply(lambda x: random.choice(filled) if pd.isnull(x) else x)

for col in ['age', 'Salary', 'city']:
        df_random[col] = random_impute(df_random[col])

display(df_random)

   id    age   Salary     city
0   1   25.0  50000.0  NewYork
1   2  100.0  60000.0   London
2   3   30.0  80000.0    Paris
3   4   35.0  80000.0    Paris
4   5  100.0  90000.0   London
5   6  100.0  90000.0    Paris